version: '3'

services:

  db:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
           - "5432:5432"

  web:
      build: .
      ports:
       - "8080:8080"