version: '3'

services:

  db:
    image: postgres:11.1
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    ports:
           - "5432:5432"

#  web:
#      build: .
#      ports:
#       - "8080:8080"

  redis:
      image: redis
#      container_name: cache
      ports:
             - "6379:6379"

  elasticsearch:
      image: elasticsearch:6.4.3
      environment:
            cluster.name: elasticsearch
      ports:
            - "9200:9200"