ALTER TABLE M_MEMBER ADD COLUMN CREATED_DATE TIMESTAMP DEFAULT NULL,
    ADD COLUMN CREATED_BY VARCHAR(200) DEFAULT NULL,
    ADD COLUMN TENANT_ID INTEGER DEFAULT NULL,
    ADD COLUMN UPDATED_DATE TIMESTAMP DEFAULT NULL,
    ADD COLUMN UPDATED_BY VARCHAR(200) DEFAULT NULL,
    ADD COLUMN GLOBAL_ID VARCHAR(200) DEFAULT NULL;