CREATE TABLE M_ROLE (
	ROLE_ID serial NOT NULL,
	ROLE_NAME varchar NOT NULL,
	ROLE_DESCRIPTION varchar NOT NULL,
	GLOBAL_ID VARCHAR(200) DEFAULT NULL,
    TENANT_ID INTEGER DEFAULT NULL,
    CREATED_DATE TIMESTAMP DEFAULT NULL,
	CREATED_BY VARCHAR(200) DEFAULT NULL,
    UPDATED_DATE TIMESTAMP DEFAULT NULL,
    UPDATED_BY VARCHAR(200) DEFAULT NULL,
	CONSTRAINT M_ROLE_PK PRIMARY KEY (ROLE_ID),
	CONSTRAINT M_ROLE_UK_NAME UNIQUE (ROLE_NAME, TENANT_ID)
);